[package]
name = "infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
domain = { path = "../domain" }
application = { path = "../application" }
ring.workspace = true
thiserror.workspace = true
argon2.workspace = true
getrandom.workspace = true
totp-rs.workspace = true
zeroize.workspace = true

[dev-dependencies]
proptest.workspace = true
tempfile.workspace = true
uuid.workspace = true
