CREATE OR REPLACE FUNCTION alert_time_valid(seconds BIGINT,nanos INTEGER)
RETURNS BOOLEAN LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $$
SELECT seconds BETWEEN -62135596800 AND 253402300799 AND nanos BETWEEN 0 AND 999999999
$$;
CREATE OR REPLACE FUNCTION alert_optional_time_valid(seconds BIGINT,nanos INTEGER)
RETURNS BOOLEAN LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
SELECT (seconds IS NULL AND nanos IS NULL) OR
    (seconds IS NOT NULL AND nanos IS NOT NULL AND
     seconds BETWEEN -62135596800 AND 253402300799 AND nanos BETWEEN 0 AND 999999999)
$$;
CREATE OR REPLACE FUNCTION alert_payload_valid(payload BYTEA,digest BYTEA)
RETURNS BOOLEAN LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $$
SELECT octet_length(payload) BETWEEN 2 AND 32768 AND digest=pg_catalog.sha256(payload)
$$;
REVOKE ALL ON FUNCTION alert_time_valid(BIGINT,INTEGER),
    alert_optional_time_valid(BIGINT,INTEGER),alert_payload_valid(BYTEA,BYTEA) FROM PUBLIC;
