pub(super) struct Spec {
    pub signature: &'static str,
    pub inputs: &'static [&'static str],
    pub outputs: &'static [&'static str],
    pub names: &'static [&'static str],
    pub result: &'static str,
    pub definer: bool,
}

pub(super) const SPECS: &[Spec] = &[
    Spec {
        signature: "password_reset_issue(uuid,text,bytea,bigint,bigint)",
        inputs: &["uuid", "text", "bytea", "bigint", "bigint"],
        outputs: &["uuid", "text", "timestamptz"],
        names: &[
            "p_id",
            "p_email",
            "p_digest",
            "p_ttl",
            "p_capacity",
            "id",
            "email",
            "expires_at",
        ],
        result: "record",
        definer: true,
    },
    Spec {
        signature: "password_reset_inspect(bytea)",
        inputs: &["bytea"],
        outputs: &["uuid", "uuid", "bigint"],
        names: &["p_digest", "id", "user_id", "auth_generation"],
        result: "record",
        definer: true,
    },
    Spec {
        signature: "password_reset_consume(uuid,bytea,uuid,bigint,text)",
        inputs: &["uuid", "bytea", "uuid", "bigint", "text"],
        outputs: &["timestamptz", "bigint", "bigint", "bigint"],
        names: &[
            "p_id",
            "p_digest",
            "p_user",
            "p_generation",
            "p_hash",
            "reset_at",
            "next_audit",
            "new_revision",
            "new_generation",
        ],
        result: "record",
        definer: true,
    },
    Spec {
        signature: "password_reset_cancel(uuid,bytea)",
        inputs: &["uuid", "bytea"],
        outputs: &[],
        names: &["p_id", "p_digest"],
        result: "void",
        definer: true,
    },
    Spec {
        signature: "password_reset_inventory_valid()",
        inputs: &[],
        outputs: &[],
        names: &[],
        result: "boolean",
        definer: true,
    },
    Spec {
        signature: "password_reset_audit_receipt()",
        inputs: &[],
        outputs: &[],
        names: &[],
        result: "trigger",
        definer: false,
    },
];
