#[allow(dead_code)]
mod case_support;
mod judicial_calendar_support;
use application::{judicial_calendars::*, ApplicationError};
use domain::{crypto::Sha256Digest, identity::UserId};
use judicial_calendar_support::*;

#[test]
fn submission_matches_independent_python_vectors_and_unicode_maximum() {
    // Generated by crates/domain/tests/fixtures/generate_judicial_calendar_vectors.py.
    let expected = include_str!("judicial_calendar_support/submission-vectors.txt");
    let actor = UserId::from_uuid(uuid::Uuid::nil());
    let digest =
        Sha256Digest::from_hex("d59dd2063ece3d13ddae7a886e9352c87d7060c9cb51a1d2560d200a0980e562")
            .unwrap();
    for (i, hex) in expected.lines().enumerate() {
        let change = match i {
            0 => JudicialCalendarChange::Publish {
                values: values("Calendar"),
            },
            1 => JudicialCalendarChange::Replace {
                expected_revision: JudicialCalendarRevision::new(u32::MAX - 1).unwrap(),
                values: values("Calendar"),
                reason: JudicialCalendarReason::new(&"\u{1f642}".repeat(1000)).unwrap(),
            },
            _ => JudicialCalendarChange::Retire {
                expected_revision: JudicialCalendarRevision::initial(),
                reason: JudicialCalendarReason::new("Retiro").unwrap(),
            },
        };
        let cmd = JudicialCalendarCommand {
            operation_id: JudicialCalendarOperationId::from_uuid(uuid::Uuid::from_u128(
                0x0123456789abcdef,
            )),
            calendar_id: JudicialCalendarId::from_uuid(uuid::Uuid::from_u128(u128::MAX)),
            change,
        };
        let bytes = judicial_calendar_submission_bytes(actor, &cmd, digest);
        let actual: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
        assert_eq!(actual, hex);
        assert_eq!(bytes.len(), [91, 4095, 101][i]);
    }
}
#[test]
fn receipt_rejects_forged_action_status_reason_revision_and_digests() {
    let actor = UserId::new();
    let original = detail(actor, &command(), values("Calendar"));
    for variant in 0..7 {
        let mut d = original.clone();
        match variant {
            0 => d.receipt.action = JudicialCalendarAction::Retire,
            1 => d.status = JudicialCalendarStatus::Retired,
            2 => d.reason = Some(JudicialCalendarReason::new("Unexpected").unwrap()),
            3 => d.revision = JudicialCalendarRevision::new(2).unwrap(),
            4 => d.values_digest = Sha256Digest::from_array([7; 32]),
            5 => d.receipt.submission_digest = Sha256Digest::from_array([7; 32]),
            _ => d.recorded_by.email = " ".into(),
        }
        assert!(matches!(
            judicial_calendar_receipt_matches(&Hasher, &d),
            Err(ApplicationError::JudicialCalendar(
                JudicialCalendarError::StoredInconsistent(_)
            ))
        ));
    }
    judicial_calendar_receipt_matches(&Hasher, &original).unwrap();
}
#[test]
fn historical_receipt_validates_without_fetching_current_values() {
    let actor = UserId::new();
    let first = detail(actor, &command(), values("Calendar"));
    let retired = detail(actor, &retirement(&first), first.values.clone());
    let entry = JudicialCalendarHistoryEntry::from(&retired);
    judicial_calendar_history_receipt_matches(&Hasher, &entry).unwrap();
    let mut bad = entry;
    bad.receipt.expected_revision = u32::MAX;
    assert!(judicial_calendar_history_receipt_matches(&Hasher, &bad).is_err());
}
