//! Names and ordered keys of the immutable and mutable alert projections.
pub(super) type Key = (&'static str, &'static str, &'static [&'static str], bool);
pub(super) const KEYS: &[Key] = &[
    (
        "alert_preferences",
        "alert_preferences_pkey",
        &["user_id", "revision"],
        true,
    ),
    (
        "alert_subject_state",
        "alert_subject_state_pkey",
        &["kind", "id"],
        true,
    ),
    (
        "alert_scan_cursor",
        "alert_scan_cursor_pkey",
        &["singleton"],
        true,
    ),
    ("alert_schedule", "alert_schedule_pkey", &["id"], true),
    (
        "alert_notifications",
        "alert_notifications_pkey",
        &["id"],
        true,
    ),
    (
        "alert_read_receipts",
        "alert_read_receipts_pkey",
        &["operation_id"],
        true,
    ),
    (
        "alert_email_outbox",
        "alert_email_outbox_pkey",
        &["id"],
        true,
    ),
    (
        "alert_email_attempts",
        "alert_email_attempts_pkey",
        &["delivery_id", "sequence"],
        true,
    ),
    (
        "alert_preferences",
        "alert_preferences_operation_id_key",
        &["operation_id"],
        false,
    ),
    (
        "alert_schedule",
        "alert_schedule_recipient_occurrence_key_key",
        &["recipient", "occurrence_key"],
        false,
    ),
    (
        "alert_notifications",
        "alert_notifications_schedule_id_key",
        &["schedule_id"],
        false,
    ),
    (
        "alert_email_outbox",
        "alert_email_outbox_alert_id_key",
        &["alert_id"],
        false,
    ),
];
pub(super) type ForeignKey = (
    &'static str,
    &'static str,
    &'static [&'static str],
    &'static str,
    &'static [&'static str],
);
pub(super) const FOREIGN_KEYS: &[ForeignKey] = &[
    (
        "alert_preferences",
        "alert_preferences_user_id_fkey",
        &["user_id"],
        "users",
        &["id"],
    ),
    (
        "alert_subject_state",
        "alert_subject_state_case_id_fkey",
        &["case_id"],
        "cases",
        &["id"],
    ),
    (
        "alert_schedule",
        "alert_schedule_case_id_fkey",
        &["case_id"],
        "cases",
        &["id"],
    ),
    (
        "alert_schedule",
        "alert_schedule_recipient_fkey",
        &["recipient"],
        "users",
        &["id"],
    ),
    (
        "alert_schedule",
        "alert_schedule_kind_subject_id_fkey",
        &["kind", "subject_id"],
        "alert_subject_state",
        &["kind", "id"],
    ),
    (
        "alert_notifications",
        "alert_notifications_schedule_id_fkey",
        &["schedule_id"],
        "alert_schedule",
        &["id"],
    ),
    (
        "alert_notifications",
        "alert_notifications_recipient_fkey",
        &["recipient"],
        "users",
        &["id"],
    ),
    (
        "alert_notifications",
        "alert_notifications_case_id_fkey",
        &["case_id"],
        "cases",
        &["id"],
    ),
    (
        "alert_notifications",
        "alert_notifications_kind_subject_id_fkey",
        &["kind", "subject_id"],
        "alert_subject_state",
        &["kind", "id"],
    ),
    (
        "alert_read_receipts",
        "alert_read_receipts_recipient_fkey",
        &["recipient"],
        "users",
        &["id"],
    ),
    (
        "alert_read_receipts",
        "alert_read_receipts_alert_id_fkey",
        &["alert_id"],
        "alert_notifications",
        &["id"],
    ),
    (
        "alert_email_outbox",
        "alert_email_outbox_alert_id_fkey",
        &["alert_id"],
        "alert_notifications",
        &["id"],
    ),
    (
        "alert_email_attempts",
        "alert_email_attempts_delivery_id_fkey",
        &["delivery_id"],
        "alert_email_outbox",
        &["id"],
    ),
];
