pub(super) const KEYS: &[(&str, &str, &[&str], bool)] = &[
    (
        "case_resource_activity_associations",
        "resource_activity_root_primary",
        &["id"],
        true,
    ),
    (
        "case_resource_activity_associations",
        "resource_activity_root_scope",
        &["id", "case_id", "resource_id"],
        false,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_revision_primary",
        &["association_id", "revision"],
        true,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_operation",
        &["operation_id"],
        false,
    ),
];
type ForeignKey = (
    &'static str,
    &'static str,
    &'static [&'static str],
    &'static str,
    &'static [&'static str],
    bool,
);
pub(super) const FOREIGN_KEYS: &[ForeignKey] = &[
    (
        "case_resource_activity_associations",
        "resource_activity_resource_root",
        &["resource_id", "case_id"],
        "case_procedural_resources",
        &["id", "case_id"],
        false,
    ),
    (
        "case_resource_activity_associations",
        "resource_activity_first_revision",
        &["id", "initial_revision"],
        "case_resource_activity_association_revisions",
        &["association_id", "revision"],
        true,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_author",
        &["recorded_by"],
        "users",
        &["id"],
        false,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_association_root",
        &["association_id", "case_id", "resource_id"],
        "case_resource_activity_associations",
        &["id", "case_id", "resource_id"],
        false,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_resource_capture",
        &["resource_id", "case_id", "resource_revision"],
        "case_procedural_resource_revisions",
        &["resource_id", "case_id", "revision"],
        false,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_resource_head",
        &["resource_id", "case_id", "recorded_resource_revision"],
        "case_procedural_resource_revisions",
        &["resource_id", "case_id", "revision"],
        false,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_act_root",
        &["act_id", "resource_id", "case_id"],
        "case_procedural_resource_acts",
        &["id", "resource_id", "case_id"],
        false,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_act_capture",
        &["resource_id", "case_id", "act_resource_revision"],
        "case_procedural_resource_revisions",
        &["resource_id", "case_id", "revision"],
        false,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_hearing_root",
        &["hearing_id", "case_id"],
        "case_hearings",
        &["id", "case_id"],
        false,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_hearing_capture",
        &["hearing_id", "hearing_revision"],
        "case_hearing_revisions",
        &["hearing_id", "revision"],
        false,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_deadline_root",
        &["deadline_id", "case_id"],
        "case_deadlines",
        &["id", "case_id"],
        false,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_deadline_capture",
        &["deadline_id", "deadline_revision"],
        "case_deadline_revisions",
        &["deadline_id", "revision"],
        false,
    ),
    (
        "case_resource_activity_association_revisions",
        "resource_activity_administration",
        &["case_id", "recorded_administration_revision"],
        "case_administration_revisions",
        &["case_id", "revision"],
        false,
    ),
];
