pub(super) const KEYS: &[(&str, &str, &[&str], bool)] = &[
    (
        "case_procedural_resources",
        "case_procedural_resources_pkey",
        &["id"],
        true,
    ),
    (
        "case_procedural_resources",
        "case_procedural_resources_id_case_id_key",
        &["id", "case_id"],
        false,
    ),
    (
        "case_procedural_resource_acts",
        "case_procedural_resource_acts_pkey",
        &["id"],
        true,
    ),
    (
        "case_procedural_resource_acts",
        "case_procedural_resource_acts_id_resource_id_case_id_key",
        &["id", "resource_id", "case_id"],
        false,
    ),
    (
        "case_procedural_resource_revisions",
        "case_procedural_resource_revisions_pkey",
        &["resource_id", "revision"],
        true,
    ),
    (
        "case_procedural_resource_revisions",
        "procedural_resource_operation_unique",
        &["operation_id"],
        false,
    ),
    (
        "case_procedural_resource_revisions",
        "case_procedural_resource_revis_resource_id_case_id_revision_key",
        &["resource_id", "case_id", "revision"],
        false,
    ),
    (
        "case_procedural_resource_revisions",
        "case_procedural_resource_revisions_act_id_act_revision_key",
        &["act_id", "act_revision"],
        false,
    ),
];
type ForeignKey = (
    &'static str,
    &'static str,
    &'static [&'static str],
    &'static str,
    &'static [&'static str],
    bool,
);
pub(super) const FOREIGN_KEYS: &[ForeignKey] = &[
    (
        "case_procedural_resources",
        "case_procedural_resources_case_id_fkey",
        &["case_id"],
        "cases",
        &["id"],
        false,
    ),
    (
        "case_procedural_resources",
        "procedural_resource_first_revision",
        &["id", "initial_revision"],
        "case_procedural_resource_revisions",
        &["resource_id", "revision"],
        true,
    ),
    (
        "case_procedural_resource_acts",
        "case_procedural_resource_acts_resource_id_case_id_fkey",
        &["resource_id", "case_id"],
        "case_procedural_resources",
        &["id", "case_id"],
        false,
    ),
    (
        "case_procedural_resource_acts",
        "procedural_resource_act_first_revision",
        &["resource_id", "case_id", "initial_resource_revision"],
        "case_procedural_resource_revisions",
        &["resource_id", "case_id", "revision"],
        true,
    ),
    (
        "case_procedural_resource_revisions",
        "case_procedural_resource_revisions_recorded_by_fkey",
        &["recorded_by"],
        "users",
        &["id"],
        false,
    ),
    (
        "case_procedural_resource_revisions",
        "case_procedural_resource_revisions_resource_id_case_id_fkey",
        &["resource_id", "case_id"],
        "case_procedural_resources",
        &["id", "case_id"],
        false,
    ),
    (
        "case_procedural_resource_revisions",
        "case_procedural_resource_revisi_act_id_resource_id_case_id_fkey",
        &["act_id", "resource_id", "case_id"],
        "case_procedural_resource_acts",
        &["id", "resource_id", "case_id"],
        false,
    ),
    (
        "case_procedural_resource_revisions",
        "case_procedural_resource_revi_case_id_recorded_administrat_fkey",
        &["case_id", "recorded_administration_revision"],
        "case_administration_revisions",
        &["case_id", "revision"],
        false,
    ),
];
