pub(super) const KEYS: &[(&str, &str, &[&str], bool)] = &[
    (
        "case_measure_operations",
        "measure_operation_primary",
        &["operation_id"],
        true,
    ),
    (
        "case_measure_operations",
        "measure_operation_scope",
        &["operation_id", "case_id"],
        false,
    ),
    (
        "case_measure_operations",
        "measure_operation_owner",
        &["operation_id", "case_id", "owner_digest"],
        false,
    ),
    (
        "case_measure_operations",
        "measure_operation_audit",
        &["audit_sequence"],
        false,
    ),
    (
        "case_measure_decisions",
        "measure_decision_primary",
        &["decision_id"],
        true,
    ),
    (
        "case_measure_decisions",
        "measure_decision_operation",
        &["operation_id"],
        false,
    ),
    (
        "case_measure_decisions",
        "measure_decision_scope",
        &["operation_id", "case_id", "group_digest"],
        false,
    ),
    ("case_measures", "measure_root_primary", &["id"], true),
    (
        "case_measures",
        "measure_root_scope",
        &["id", "case_id"],
        false,
    ),
    (
        "case_measure_revisions",
        "measure_revision_primary",
        &["measure_id", "revision"],
        true,
    ),
    (
        "case_measure_revisions",
        "measure_revision_scope",
        &["measure_id", "revision", "case_id", "owner_operation"],
        false,
    ),
];

type ForeignKey = (
    &'static str,
    &'static str,
    &'static [&'static str],
    &'static str,
    &'static [&'static str],
    bool,
);
pub(super) const FOREIGN_KEYS: &[ForeignKey] = &[
    (
        "case_measure_operations",
        "measure_operation_case",
        &["case_id"],
        "cases",
        &["id"],
        false,
    ),
    (
        "case_measure_operations",
        "measure_operation_audit_event",
        &["audit_sequence"],
        "audit_events",
        &["sequence"],
        true,
    ),
    (
        "case_measure_operations",
        "measure_operation_payload",
        &["operation_id", "case_id", "owner_digest"],
        "case_measure_decisions",
        &["operation_id", "case_id", "group_digest"],
        true,
    ),
    (
        "case_measure_decisions",
        "measure_decision_owner",
        &["operation_id", "case_id", "group_digest"],
        "case_measure_operations",
        &["operation_id", "case_id", "owner_digest"],
        true,
    ),
    (
        "case_measure_decisions",
        "measure_decision_administration",
        &["case_id", "observed_administration_revision"],
        "case_administration_revisions",
        &["case_id", "revision"],
        false,
    ),
    (
        "case_measure_decisions",
        "measure_decision_author",
        &["recorded_by"],
        "users",
        &["id"],
        false,
    ),
    (
        "case_measure_decisions",
        "measure_decision_anchor_hearing",
        &["anchor_hearing_id", "anchor_revision"],
        "case_hearing_revisions",
        &["hearing_id", "revision"],
        false,
    ),
    (
        "case_measure_decisions",
        "measure_decision_anchor_precautionary",
        &["anchor_precautionary_hearing_id", "anchor_revision"],
        "case_precautionary_hearing_revisions",
        &["hearing_id", "revision"],
        false,
    ),
    (
        "case_measures",
        "measure_root_owner",
        &["root_operation", "case_id"],
        "case_measure_operations",
        &["operation_id", "case_id"],
        false,
    ),
    (
        "case_measures",
        "measure_root_first_revision",
        &["id", "initial_revision", "case_id", "root_operation"],
        "case_measure_revisions",
        &["measure_id", "revision", "case_id", "owner_operation"],
        true,
    ),
    (
        "case_measure_revisions",
        "measure_revision_root",
        &["measure_id", "case_id"],
        "case_measures",
        &["id", "case_id"],
        true,
    ),
    (
        "case_measure_revisions",
        "measure_revision_owner",
        &["owner_operation", "case_id"],
        "case_measure_operations",
        &["operation_id", "case_id"],
        true,
    ),
    (
        "case_measure_revisions",
        "measure_revision_subject",
        &["subject_id", "subject_revision"],
        "case_subject_revisions",
        &["subject_id", "revision"],
        false,
    ),
];
