nextest-version = "0.9.146"

[store]
dir = "output/nextest"

[profile.ci]
retries = 0
fail-fast = false
status-level = "fail"
final-status-level = "fail"
failure-output = "final"

[profile.ci.junit]
path = "junit.xml"
store-success-output = false
