pub(super) const KEYS: &[(&str, &str, &[&str], bool)] = &[
    (
        "case_resource_hearings",
        "resource_hearing_root_primary",
        &["id"],
        true,
    ),
    (
        "case_resource_hearings",
        "resource_hearing_root_scope",
        &["id", "case_id", "resource_id"],
        false,
    ),
    (
        "case_resource_hearing_revisions",
        "resource_hearing_revision_primary",
        &["hearing_id", "revision"],
        true,
    ),
    (
        "case_resource_hearing_revisions",
        "resource_hearing_revision_scope",
        &["hearing_id", "case_id", "resource_id", "revision"],
        false,
    ),
    (
        "case_resource_hearing_revisions",
        "resource_hearing_operation",
        &["operation_id"],
        false,
    ),
];
type ForeignKey = (
    &'static str,
    &'static str,
    &'static [&'static str],
    &'static str,
    &'static [&'static str],
    bool,
);
pub(super) const FOREIGN_KEYS: &[ForeignKey] = &[
    (
        "case_resource_hearings",
        "resource_hearing_resource_root",
        &["resource_id", "case_id"],
        "case_procedural_resources",
        &["id", "case_id"],
        false,
    ),
    (
        "case_resource_hearings",
        "resource_hearing_first_revision",
        &["id", "initial_revision"],
        "case_resource_hearing_revisions",
        &["hearing_id", "revision"],
        true,
    ),
    (
        "case_resource_hearing_revisions",
        "resource_hearing_author",
        &["recorded_by"],
        "users",
        &["id"],
        false,
    ),
    (
        "case_resource_hearing_revisions",
        "resource_hearing_revision_root",
        &["hearing_id", "case_id", "resource_id"],
        "case_resource_hearings",
        &["id", "case_id", "resource_id"],
        false,
    ),
    (
        "case_resource_hearing_revisions",
        "resource_hearing_resource_capture",
        &["resource_id", "case_id", "resource_revision"],
        "case_procedural_resource_revisions",
        &["resource_id", "case_id", "revision"],
        false,
    ),
    (
        "case_resource_hearing_revisions",
        "resource_hearing_resource_head",
        &["resource_id", "case_id", "recorded_resource_revision"],
        "case_procedural_resource_revisions",
        &["resource_id", "case_id", "revision"],
        false,
    ),
    (
        "case_resource_hearing_revisions",
        "resource_hearing_act_root",
        &["act_id", "resource_id", "case_id"],
        "case_procedural_resource_acts",
        &["id", "resource_id", "case_id"],
        false,
    ),
    (
        "case_resource_hearing_revisions",
        "resource_hearing_act_capture",
        &["resource_id", "case_id", "act_resource_revision"],
        "case_procedural_resource_revisions",
        &["resource_id", "case_id", "revision"],
        false,
    ),
    (
        "case_resource_hearing_revisions",
        "resource_hearing_administration",
        &["case_id", "recorded_administration_revision"],
        "case_administration_revisions",
        &["case_id", "revision"],
        false,
    ),
    (
        "case_resource_hearing_revisions",
        "resource_hearing_association_root",
        &["association_id", "case_id", "resource_id"],
        "case_resource_activity_associations",
        &["id", "case_id", "resource_id"],
        true,
    ),
];
